### ISSUE TITLE
Compatibilidade Split e necessidade de gps

### ISSUE THREAD

**Issue by felipesalomao** [somosprte/maquininha-wirecard-react-native#7]
Olá, a biblioteca parece bem interessante. Não comecei integrar ainda. 
1 - Tenho duas dúvidas, prevê casos de uso para split de pagamento?
No teste que fiz no app padrão em um celular low end, demorou demais entre enviar a ordem e a máquina estar pronta para passar o cartão, em grande parte por conta da geolocalização que demorou muito para retornar. De 15 segundos, 11 foram para pegar geo localização. Sabe dizer se é possível fazer pagamento sem ter que em toda transação ter que pegar localização? Caso seja obrigatório, posso informar uma localização pré determinada sem ter que de fato contuar localização do gps? Pois quando sinal tá fraco (dentro de Edificio), costuma demorar muito prejudicando muito experiência do usuário. 

Parabéns pela lib. 

Att,
Felipe.

**Comment by lucasGabrielDeAA** [comment]
Olá,
1 - O split de pagamentos não foi implementado nessa versão da lib. Pois esta versão do app de exemplo foi idealizado baseado em uma necessidade nossa, mas a parte do split, já está no nosso radar, para implementação em uma versão futura, já que basta seguir a documentação oficial da lib da própria wirecard.
2 -  A respeito da geolocalização, não tivemos em nenhum momento essa questão, pois a geolocalização é solicitada após a instalação do app de exemplo, juntamente com as demais permissões do dispositivo Android, a documentação oficial não fala nada a respeito de solicitação da geolocalização em todo pagamento. Iremos verificar isso também.

Muito obrigado, e o mais importante, muito obrigado pelo seu feedback.

Att,
Lucas Gabriel

**Comment by felipesalomao** [comment]
Entendi. Se puder tirar só uma dúvida, quando envia ordem de Paganento para máquina, entre enviar e ela estar pronta para passar cartão, demora quanto tempo com essa lib? Rápido? Quantos segundos em média? É que no app oficial demorou bastante por conta de toda vez pegar geolocalização.

**Comment by lucasGabrielDeAA** [comment]
> Entendi. Se puder tirar só uma dúvida, quando envia ordem de Paganento para máquina, entre enviar e ela estar pronta para passar cartão, demora quanto tempo com essa lib? Rápido? Quantos segundos em média? É que no app oficial demorou bastante por conta de toda vez pegar geolocalização.

Claro...
Então, essa informação é algo que eu nunca mensurei aqui. Mas com toda certeza não demora os 15 segundos que você informou, que é o que acontece no app oficial. Creio que deva levar uma média de 5 -7 segundos. Mas não sei te precisar esta informação.

**Comment by felipesalomao** [comment]
Show de bola. Já iria melhorar bastante esse tempo.. mais natural. O app original tá bem abandonado.. vou implementar aqui inclusive devo colocar split. Tendo sucesso compartilho o código. Muito Obrigado.
